version: "3.9"

services:
  web:
    build: .
    container_name: academy_web
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 academy.asgi:application"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "8000:8000"   # <-- add this

  celery_worker:
    build: .
    container_name: academy_celery_worker
    command: celery -A academy worker -l info -P solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7
    container_name: academy_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: academy_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # management UI
  celery_beat:
    build: .
    container_name: academy_celery_beat
    command: celery -A academy beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
  nginx:
    image: nginx:alpine
    container_name: academy_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static  # if you use collectstatic
    ports:
      - "80:80"
    depends_on:
      - web

