# version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: academy_db
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: academy_web
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 academy.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    environment:
      - DJANGO_COLLECTSTATIC=1
      - DJANGO_MIGRATE=1
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8000:8000"   # <-- add this
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  celery_worker:
    build: .
    container_name: academy_celery_worker
    command: celery -A academy worker -l info -P solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7
    container_name: academy_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: academy_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # management UI
  celery_beat:
    build: .
    container_name: academy_celery_beat
    command: celery -A academy beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
  nginx:
    image: nginx:alpine
    container_name: academy_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
  flower:
      image: mher/flower
      container_name: academy_flower
      command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --basic_auth=user:pass
      env_file:
        - .env
      ports:
        - "5555:5555"
      depends_on:
        - rabbitmq
        - redis

volumes:
  postgres_data:
  static_volume: